### ISSUE TITLE
base32 needs correction

### ISSUE THREAD

**Issue by My1** [bbars/utils#1]
according to
https://tools.ietf.org/html/rfc2938#section-3.1.2
this is called base32, BUT

https://tools.ietf.org/html/rfc4648#section-7
states that this base-32 encoding based on an extended hex alphabet should not be called "base32" and base32hex may be used instead.

the "real" base32 is described here:
https://tools.ietf.org/html/rfc4648#section-6
which basically uses a different character set, and uses all the letters at the start and the numbers 2 to 7 (234567) at the end.

**Comment by bbars** [comment]
Thank you, fixed at 2be09aa
